const networkEvents = {
  PLAYER_CONNECTED: 'PLAYER_CONNECTED',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  GAME_TICK: 'GAME_TICK',
  GAME_START: 'GAME_START',
  GAME_STARTED: 'GAME_STARTED',
  GAME_END: 'GAME_END',
  GAME_ENDED: 'GAME_ENDED',
  ERROR: 'ERROR',
};

export default networkEvents;
